version: '3.9'

services:
    collabora:
        container_name: collabora
        image: collabora/code:latest
        restart: always
        environment:
#            - username=admin
#            - password=b1gl1nux@collabora
            - aliasgroup1= https://localhost:9980, http://localhost:8286
            - extra_params=-o:welcome.enable=false
            - dictionaries=en_US es_ES pt_BR pt_PT
        #volumes:
            #- ${HOME}/Docker/Nextcloud-Plus/Collabora/fonts/truetype:/usr/share/fonts/truetype
            #- ${HOME}/Docker/Nextcloud-Plus/Collabora/fonts/truetype:/opt/cool/systemplate/usr/share/fonts/truetype
        ports:
            - "9980:9980"
        deploy:
            resources:
                limits:
                    # Limits the CPU usage by the container to 4 cores.
                    cpus: '4'
                    # Limits the memory usage by the container to 4GB.
                    memory: 4G
        healthcheck:
            # Checks the health of the container using curl to access port 9980.
            test: ["CMD", "curl", "-f", "https://127.0.0.1:9980"]
            # The interval between each health check.
            interval: 30s
            # The maximum amount of time a health check can take before it is considered a failure.
            timeout: 10s
            # The number of consecutive health check failures required for the container to be considered unhealthy.
            retries: 6
        # Network the container will be connected to.
        networks:
            - collabora-net

# Defines the networks that will be created
networks:
    # Network name
    collabora-net:
        # Name assigned to the network
        name: collabora-net
